services:
  resourceavailability:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resourceavailability
    volumes:
      - ./reports:/reports:rw
    environment:
      - TS_NAME=localtestrun
      - TEST_URL=https://brugge-ldes.geomobility.eu/observations
      - TEST_MAX-REDIRECTS=3
      - TEST_TIMEOUT=10
      - TEST_CHECK_HTTP_AVAILABILITY=TRUE
      - TEST_CHECK_HTTPS_AVAILABILITY=TRUE
      - TEST_VERIFY-SSL=TRUE
    working_dir: /app
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
