services:
  resourceavailability:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resourceavailability
    volumes:
      - ./reports:/reports:rw
    environment:
      - TS_NAME=localtestrun
      - TEST_URLS=[https://brugge-ldes.geomobility.eu/observations, https://ldes.telraam-api.net/locations]
      - TEST_MAX-REDIRECTS=3
      - TEST_TIMEOUT=10
      - TEST_CHECK-HTTP-AVAILABILITY=TRUE
      - TEST_CHECK-HTTPS-AVAILABILITY=TRUE
      - TEST_VERIFY-SSL=TRUE
    working_dir: /app
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
